services:
  letslive:
    build:
      context: .
      dockerfile: Dockerfile
    image: letslive:latest
    container_name: letsliveglobal
    ports:
      - "8000:8000"
    environment:
      POSTGRES_HOST: database
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: lets-live
      POSTGRES_PORT: 5432
    volumes:
      - .:/app
    depends_on:
      - database

  database:
    image: postgres:16.3
    container_name: postgres_db
    shm_size: 128mb
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: lets-live
    volumes:
      - postgres_data:/var/lib/postgresql/data

  ui:
    build:
      context: ./ui
      dockerfile: Dockerfile
    image: letslive_ui:latest
    container_name: letsliveglobal_ui
    ports:
      - "5000:5000"
    depends_on:
      - letslive

volumes:
  postgres_data:
