spring:
  application:
    name: configserver
  port: 8181
  cloud:
    config:
      server:
        git:
          uri: "https://github.com/ThNam203/letslive-configs.git"
          default-label: main
          timeout: 10
          clone-on-start: true
          force-pull: true

logging:
  level:
    org:
      springframework:
        cloud: DEBUG

management:
  endpoints:
    web:
      exposure:
        include: "*"
  health:
    readiness-state:
      enabled: true
    liveness-state:
      enabled: true
  endpoint:
    health:
      probes:
        enabled: true
