# postgres-pv.yaml
apiVersion: v1
kind: PersistentVolume
metadata:
  name: postgres-auth-pv
spec:
  capacity:
    storage: 100Mi
  accessModes:
    - ReadWriteOnce
  hostPath: 
    path: /data/postgres

---

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: postgres-auth-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 100Mi
