apiVersion: apps/v1
kind: Deployment
metadata:
  name: letslive-auth-deployment
  labels:
    app: letslive-auth
spec:
  replicas: 1
  selector:
    matchLabels:
      app: letslive-auth
  template: # configuration for each pod
    metadata:
      labels:
        app: letslive-auth
    spec:
      containers:
      - image: letslive/auth
        name: letslive-auth
        ports:
          - containerPort: 7777
        protocol: TCP
      containers:
      - name: postgres
        image: postgres:latest
        env:
          - name: POSTGRES_DB
            value: letslive-auth
          - name: POSTGRES_USER
            valueFrom:
              secretKeyRef:
                name: postgres-auth-db-secret
                key: POSTGRES_USER
          - name: POSTGRES_PASSWORD
            valueFrom:
              secretKeyRef:
                name: postgres-auth-db-secret
                key: POSTGRES_PASSWORD
        ports:
          - containerPort: 5432
        volumeMounts:
          - mountPath: /var/lib/postgresql/data
            name: postgres-auth-volume
      volumes:
        - name: postgres-auth-volume
          persistentVolumeClaim:
            claimName: postgres-pvc
