publicHLSPath: public/hls
privateHLSPath: private/hls
webServerPort: 8889

ffmpegSetting:
  ffmpegPath: /usr/bin/ffmpeg
  masterFileName: index.m3u8
  hlsTime: 2
  crf: 21
  preset: ultrafast
  hlsListSize: 10
  hlsMaxSize: 20

  qualities:
    - resolution: 640x360
      maxBitrate: 365k
      fps: 30
      bufSize: 730k
    - resolution: 1280x720
      maxBitrate: 4.5M
      fps: 60
      bufSize: 9M
    - resolution: 1920x1080
      maxBitrate: 7.8M
      fps: 60
      bufSize: 15.6M

ipfs:
  enabled: true
  gateway: http://127.0.0.1:8080

loadBalancer:
  http:
    name: http-load-balancer
    from: 8888
    to:
      - http://0.0.0.0:8889
  tcp:
    name: tcp-load-balancer
    from: 0.0.0.0:1935
    to:
      - localhost:1936

